### ISSUE TITLE
Tomcat 8 support regression

### ISSUE THREAD

**Issue by dabdine-r7** [aws/aws-dynamodb-session-tomcat#26]
It appears this commit introduced tomcat 8 support (tomcat-catalina dependency of 8.0.14):
https://github.com/aws/aws-dynamodb-session-tomcat/commit/5cc688fd3a2a9544f756c19a687696f1df2941e8

However, this commit reverted the tomcat-catalina dependency back to 7.0.47 (looks like it may have been related to conflicts / a bad merge):
https://github.com/aws/aws-dynamodb-session-tomcat/commit/e9214bcf73462ba929652025404a95f8689430b4

It may be better to either fork this repository (aws-dynamodb-session-tomcat8) or fork the versions in this repository to maintain compatibility with both tomcat7 and tomcat8.

As a result, I get this in my logs:

    08-Jul-2015 03:43:09.906 SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren Exception invoking periodic operation: 
     java.lang.NoSuchMethodError: org.apache.catalina.Container.getLoader()Lorg/apache/catalina/Loader;
	at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStore.load(DynamoDBSessionStore.java:121)
	at org.apache.catalina.session.StoreBase.processExpires(StoreBase.java:144)
	at org.apache.catalina.session.PersistentManagerBase.processExpires(PersistentManagerBase.java:428)
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:555)
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5532)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1378)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1382)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1382)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1350)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dabdine-r7** [comment]
Seems like this was pebkac on my part. I was using the 1.0.3 release. The changes mentioned above still work fine even though the lib was downgraded (it's in the provided scope so that doesn't really matter anyway).

It'd be nice to get an official 2.0.0 release, though.

Closing down...

**Comment by shorea** [comment]
We build against Tomcat 7 to make sure we aren't using any new APIs that would break Tomcat7 support but we test and support Tomcat8.

**Comment by MiaShopgal** [comment]
thanks to @dabdine-r7, I just got the same error, cos I'm following the [documentation](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-tomcat-session-manager.html) to look for jar file like AmazonDynamoDBSessionManagerForTomcat-**1.x.x**.jar
